name: Flaky Specs Reporter

on:
  # schedule:
  #   - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  flaky-specs-reporter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.2

    - name: Install Octokit
      run: gem install octokit rubyzip

    - name: Run Flaky Consolidation
      run: ruby ./scripts/consolidate_flaky.rb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPO_NAME: ${{ github.repository }}
        GITHUB_WORKFLOW_FILE: 'run-tests.yml'
        GITHUB_BRANCH: "main"
        GH_PAT: ${{ secrets.GITHUB_PAT }}
